# version: "3.3"

# services:
#   postgres:
#     image: postgres:${SOFTWARE_VERSION_TAG}
#     restart: always
#     expose:
#       - ${DATABASE_PORT}
#     environment:
#       PGPORT: ${DATABASE_PORT}
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#       PGDATA: /var/lib/postgresql/data
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data

#   botpress:
#     image: botpress/server:${SOFTWARE_VERSION_TAG}
#     restart: always
#     expose:
#       - 3000
#     ports:
#       - "3000"
#     volumes:
#       - ./botpress_data:/botpress/data
#     environment:
#       - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:5435/${DB_NAME}
#       - EXTERNAL_URL=${EXTERNAL_URL}
#       # - PORT=8080
#       # - BP_HOST=0.0.0.0
#       # - NODE_ENV=production
#       # - PG_HOST=${DATABASE_HOST}
#       # - PG_PORT=${DATABASE_PORT}
#       # - PG_USER=${DB_USER}
#       # - PG_PASSWORD=${DB_PASS}
#       # - PG_SSL=false
#     depends_on:
#       - postgres

#   nginx:
#     image: jonasal/nginx-certbot:latest
#     restart: unless-stopped
#     environment:
#       - CERTBOT_EMAIL=${ADMIN_EMAIL}
#     ports:
#       - 172.17.0.1:4765::80
#     volumes:
#       - ./nginx_secrets:/etc/letsencrypt
#       - ./nginx/user_conf.d:/etc/nginx/user_conf.d

version: "3.3"

services:
  botpress:
    image: botpress/server:${SOFTWARE_VERSION_TAG}
    ports:
      - 3000
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:5435/${DB_NAME}
      - BP_MODULE_NLU_DUCKLINGURL=http://botpress_lang:8000
      - BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"http://botpress_lang:3100"}]
      - EXTERNAL_URL=${EXTERNAL_URL}
    depends_on:
      - botpress_lang
      - postgres
    volumes:
      - ./botpress_data:/botpress/data

  botpress_lang:
    image: botpress/server
    container_name: botpress-lang
    command: bash -c "./duckling -p 8000 & ./bp lang --langDir /botpress/lang --port 3100"
    expose:
      - 3100
      - 8000
    volumes:
      - ./botpress_language:/botpress/lang

  postgres:
    image: postgres:11.2-alpine
    expose:
      - 5435
    container_name: postgres
    environment:
      PGPORT: 5435
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21
    ports:
      - 172.17.0.1:4765:80
    command: nginx -g 'daemon off';
    depends_on:
      - botpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
