version: "3.3"

services:
  postgres:
    image: postgres:${SOFTWARE_VERSION_TAG}
    restart: always
    expose:
      - ${DATABASE_PORT}
    environment:
      PGPORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  botpress:
    image: botpress/server:${SOFTWARE_VERSION_TAG}
    restart: always
    expose:
      - 3000
    ports:
      - "3000"
    volumes:
      - ./botpress_data:/botpress/data
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:5435/${DB_NAME}
      - EXTERNAL_URL=${EXTERNAL_URL}
      # - PORT=8080
      # - BP_HOST=0.0.0.0
      # - NODE_ENV=production
      # - PG_HOST=${DATABASE_HOST}
      # - PG_PORT=${DATABASE_PORT}
      # - PG_USER=${DB_USER}
      # - PG_PASSWORD=${DB_PASS}
      # - PG_SSL=false
    depends_on:
      - postgres

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${ADMIN_EMAIL}
    ports:
      - 172.17.0.1:4765::80
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
